"""article_description_renamed

Revision ID: 4143b65eccf4
Revises: c6e1f1bd7e55
Create Date: 2024-01-04 11:27:01.051427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '4143b65eccf4'
down_revision: Union[str, None] = 'c6e1f1bd7e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('content', sa.Text(), nullable=True))
    op.drop_column('articles', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('articles', 'content')
    # ### end Alembic commands ###
